In [2]:
# import libraries

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, GRU


In [25]:
#1 Generate Sequence

sequence = np.array([i for i in range(1,201)])

In [26]:
#2 prepare input-output pairs

x,y = [],[]
time_steps= 5

for i in range (len(sequence)-time_steps):
  x.append(sequence[i:i+time_steps])
  y.append(sequence[i+time_steps])

x = np.array(x)
y = np.array(y)

In [27]:
x

array([[  1,   2,   3,   4,   5],
       [  2,   3,   4,   5,   6],
       [  3,   4,   5,   6,   7],
       [  4,   5,   6,   7,   8],
       [  5,   6,   7,   8,   9],
       [  6,   7,   8,   9,  10],
       [  7,   8,   9,  10,  11],
       [  8,   9,  10,  11,  12],
       [  9,  10,  11,  12,  13],
       [ 10,  11,  12,  13,  14],
       [ 11,  12,  13,  14,  15],
       [ 12,  13,  14,  15,  16],
       [ 13,  14,  15,  16,  17],
       [ 14,  15,  16,  17,  18],
       [ 15,  16,  17,  18,  19],
       [ 16,  17,  18,  19,  20],
       [ 17,  18,  19,  20,  21],
       [ 18,  19,  20,  21,  22],
       [ 19,  20,  21,  22,  23],
       [ 20,  21,  22,  23,  24],
       [ 21,  22,  23,  24,  25],
       [ 22,  23,  24,  25,  26],
       [ 23,  24,  25,  26,  27],
       [ 24,  25,  26,  27,  28],
       [ 25,  26,  27,  28,  29],
       [ 26,  27,  28,  29,  30],
       [ 27,  28,  29,  30,  31],
       [ 28,  29,  30,  31,  32],
       [ 29,  30,  31,  32,  33],
       [ 30,  

In [28]:
y

array([  6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,
        19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,
        32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,
        45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
        58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
        71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
        84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,
        97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
       110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122,
       123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135,
       136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148,
       149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161,
       162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174,
       175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 18

In [29]:
#3 reshape input for GRU (samples, time steos, features)

x= x.reshape((x.shape[0],x.shape[1],1))

In [30]:
x

array([[[  1],
        [  2],
        [  3],
        [  4],
        [  5]],

       [[  2],
        [  3],
        [  4],
        [  5],
        [  6]],

       [[  3],
        [  4],
        [  5],
        [  6],
        [  7]],

       [[  4],
        [  5],
        [  6],
        [  7],
        [  8]],

       [[  5],
        [  6],
        [  7],
        [  8],
        [  9]],

       [[  6],
        [  7],
        [  8],
        [  9],
        [ 10]],

       [[  7],
        [  8],
        [  9],
        [ 10],
        [ 11]],

       [[  8],
        [  9],
        [ 10],
        [ 11],
        [ 12]],

       [[  9],
        [ 10],
        [ 11],
        [ 12],
        [ 13]],

       [[ 10],
        [ 11],
        [ 12],
        [ 13],
        [ 14]],

       [[ 11],
        [ 12],
        [ 13],
        [ 14],
        [ 15]],

       [[ 12],
        [ 13],
        [ 14],
        [ 15],
        [ 16]],

       [[ 13],
        [ 14],
        [ 15],
        [ 16],
        [ 17]],


In [31]:
#4 buil GRU model
model= Sequential()
model.add(GRU(50,activation='relu',input_shape=(time_steps,1)))
model.add(Dense(1))

In [32]:
#5 compile model

model.compile(optimizer='adam',loss='mse')

In [33]:
#6 train model

model.fit(x,y,epochs= 100, verbose=0)

In [35]:
#7 test presdictions

test_input= np.array([196,197,198,199,200])
test_input= test_input.reshape(1,time_steps,1)
model.predict(test_input,verbose=0)

array([[200.9136]], dtype=float32)